markdown: redcarpet
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
redcarpet:
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data" ]

title: EN0572
subtitle: Operating systems and concurrency
authors: Michael Brockway, David Kendall, Alun Moon
copyyear: 2015
url: http://hesabu.net/en0572
raurl: http://hesabu.net/en0572/assets/ra
#url: http://localhost:4000
#raurl: http://localhost:4000/assets/ra

lab_links:
  - title: Lab 2 - Blinky
    url: L02.html
  - title: Lab 3 - Buttons
    url: L03.html
  - title: Lab 4 - Interrupts
    url: L04.html

right_links:
  - title: View on GitHub
    url: https://github.com/davidkendall/en0572

repo: https://github.com/davidkendall/en0572

