markdown: redcarpet
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
redcarpet:
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", disable_indented_code_blocks, "autolink", "tables", "with_toc_data" ]

title: CM0605
subtitle: Embedded systems engineering
authors: Michael Brockway, David Kendall
copyyear: 2015-2017
#url: http://hesabu.net/cm0605
raurl: assets/ra
rraurl: assets/ra
#url: http://localhost:4000
#raurl: http://localhost:4000/assets/ra

lab_links:
  - title: Lab 1 - ISR, Timers
    url: assets/ra/L01.pdf
    rep: cm0605_lab01
  - title: Lab 3 - Time-triggered scheduler
    url: assets/ra/L03.pdf
    rep: cm0605_lab03
  - title: Lab 5 - uCOS-II
    url: assets/ra/L05.pdf
    rep: cm0605_lab05
  - title: Lab 7 - Measuring software execution time
    url: assets/ra/L07.pdf
    rep: cm0605_lab07
  - title: Lab 9 - Controller Area Network (CAN)
    url: assets/ra/L09.pdf
    rep: cm0605_lab09
 

right_links:
  - title: View on GitHub
    url: https://github.com/davidkendall/cm0605_www

repo: https://github.com/davidkendall/cm0605

